'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@orchestra-design-system/core/client";
import type { Components } from "@orchestra-design-system/core/dist/components";
import { OrchestraButton as OrchestraButtonElement } from "@orchestra-design-system/core/dist/components/orchestra-button.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type OrchestraButtonEvents = NonNullable<unknown>;

export const OrchestraButton: StencilReactComponent<OrchestraButtonElement, OrchestraButtonEvents, Components.OrchestraButton> = /*@__PURE__*/ createComponent<OrchestraButtonElement, OrchestraButtonEvents, Components.OrchestraButton>({
    tagName: 'orchestra-button',
    properties: {
        text: 'text',
        type: 'type',
        variant: 'variant',
        disabled: 'disabled',
        size: 'size',
        icon: 'icon',
        iconName: 'icon-name'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@orchestra-design-system/core/hydrate') as Promise<HydrateModule>) : undefined,
    // @ts-ignore - clientModule not available in current setup
    clientModule: clientComponents.OrchestraButton as StencilReactComponent<OrchestraButtonElement, OrchestraButtonEvents, Components.OrchestraButton>,
    serializeShadowRoot
});
