'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@orchestra-kit/core/dist/components";
import { OrchestraButton as OrchestraButtonElement, defineCustomElement as defineOrchestraButton } from "@orchestra-kit/core/dist/components/orchestra-button.js";

export type OrchestraButtonEvents = NonNullable<unknown>;

export const OrchestraButton: StencilReactComponent<OrchestraButtonElement, OrchestraButtonEvents, Components.OrchestraButton> = /*@__PURE__*/ createComponent<OrchestraButtonElement, OrchestraButtonEvents, Components.OrchestraButton>({
    tagName: 'orchestra-button',
    elementClass: OrchestraButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as OrchestraButtonEvents,
    defineCustomElement: defineOrchestraButton
});
