'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@orchestra-design-system/core/client";
import type { Components } from "@orchestra-design-system/core/dist/components";
import { OrchestraCheckbox as OrchestraCheckboxElement } from "@orchestra-design-system/core/dist/components/orchestra-checkbox.js";
import type { OrchestraCheckboxCustomEvent } from "@orchestra-design-system/core";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type OrchestraCheckboxEvents = { onOrchestraChange: EventName<OrchestraCheckboxCustomEvent<boolean>> };

// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
export const OrchestraCheckbox: StencilReactComponent<OrchestraCheckboxElement, OrchestraCheckboxEvents, Components.OrchestraCheckbox> = /*@__PURE__*/ createComponent<OrchestraCheckboxElement, OrchestraCheckboxEvents, Components.OrchestraCheckbox>({
  tagName: 'orchestra-checkbox',
  properties: {
    variant: 'variant',
    checked: 'checked',
    disabled: 'disabled',
    name: 'name',
    value: 'value',
    ariaLabel: 'aria-label',
    ariaLabelledBy: 'aria-labelledby'
  },
  hydrateModule: typeof window === 'undefined' ? (import('@orchestra-design-system/core/hydrate') as Promise<HydrateModule>) : undefined,
  // @ts-ignore - clientModule not available in current setup
  clientModule: clientComponents.OrchestraCheckbox as StencilReactComponent<OrchestraCheckboxElement, OrchestraCheckboxEvents, Components.OrchestraCheckbox>,
  serializeShadowRoot
});
