'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@orchestra-kit/core/dist/components";
import { OrchestraIcon as OrchestraIconElement, defineCustomElement as defineOrchestraIcon } from "@orchestra-kit/core/dist/components/orchestra-icon.js";

export type OrchestraIconEvents = NonNullable<unknown>;

export const OrchestraIcon: StencilReactComponent<OrchestraIconElement, OrchestraIconEvents, Components.OrchestraIcon, 'name'> = /*@__PURE__*/ createComponent<OrchestraIconElement, OrchestraIconEvents, Components.OrchestraIcon, 'name'>({
    tagName: 'orchestra-icon',
    elementClass: OrchestraIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as OrchestraIconEvents,
    defineCustomElement: defineOrchestraIcon
});
