'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@orchestra-kit/core/client";
import type { Components } from "@orchestra-kit/core/dist/components";
import { OrchestraIcon as OrchestraIconElement } from "@orchestra-kit/core/dist/components/orchestra-icon.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type OrchestraIconEvents = NonNullable<unknown>;

export const OrchestraIcon: StencilReactComponent<OrchestraIconElement, OrchestraIconEvents, Components.OrchestraIcon> = /*@__PURE__*/ createComponent<OrchestraIconElement, OrchestraIconEvents, Components.OrchestraIcon>({
    tagName: 'orchestra-icon',
    properties: {
        name: 'name',
        library: 'library',
        fill: 'fill',
        size: 'size'
    },
    hydrateModule: typeof window === 'undefined' ? (import('@orchestra-kit/core/hydrate') as Promise<HydrateModule>) : undefined,
    clientModule: clientComponents.OrchestraIcon as StencilReactComponent<OrchestraIconElement, OrchestraIconEvents, Components.OrchestraIcon>,
    serializeShadowRoot
});
