'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type OrchestraCheckboxCustomEvent } from "@orchestra-design-system/core";
import type { Components } from "@orchestra-design-system/core/dist/components";
import { OrchestraCheckbox as OrchestraCheckboxElement, defineCustomElement as defineOrchestraCheckbox } from "@orchestra-design-system/core/dist/components/orchestra-checkbox.js";

export type OrchestraCheckboxEvents = { onOrchestraChange: EventName<OrchestraCheckboxCustomEvent<boolean>> };

export const OrchestraCheckbox: StencilReactComponent<OrchestraCheckboxElement, OrchestraCheckboxEvents, Components.OrchestraCheckbox> = /*@__PURE__*/ createComponent<OrchestraCheckboxElement, OrchestraCheckboxEvents, Components.OrchestraCheckbox>({
    tagName: 'orchestra-checkbox',
    elementClass: OrchestraCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onOrchestraChange: 'orchestraChange' } as OrchestraCheckboxEvents,
    defineCustomElement: defineOrchestraCheckbox
});
