/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OrchestraButton {
        /**
          * A boolean indicating the disable state of the button. The `aria-disabled` attribute relies on this property.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * It allows to render the chosen icon.  The icon render only if `iconName` and `iconPosition` are defined.
          * @default 'none'
         */
        "icon"?: 'only' | 'start' | 'end' | 'none';
        /**
          * Accept all icon names from
          * @pollux-docaposte /icon-library. By using the core-button component you don't have to install it as dependency.  The icon render only if `iconName` and `iconPosition` are defined.
          * @default undefined
         */
        "iconName"?: string;
        /**
          * A string indicating the size variation of the button.
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * This is the text which appear inside the button. It is required.
         */
        "text": string;
        /**
          * A string indicating the behavior of the button. It relies on `HTMLButtonElement['type']`
          * @default 'button'
         */
        "type"?: HTMLButtonElement['type'];
        /**
          * A string indicating the design variation of the button based on the level of importance.
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'tertiary';
    }
    interface OrchestraIcon {
        /**
          * Taking the currentcolor (inherited color of the font) by default, except if specified.
          * @default 'currentcolor'
         */
        "fill"?: string | 'currentcolor';
        /**
          * The name of the icon library to use. Defaults to 'core'.
          * @default 'core'
         */
        "library": string;
        /**
          * The name of the icon to display. Resolves using registered icon libraries.
         */
        "name": string;
        /**
          * Taking the size of the parent element by default, except if specified.
          * @default '100%'
         */
        "size"?: string | '100%';
    }
}
declare global {
    interface HTMLOrchestraButtonElement extends Components.OrchestraButton, HTMLStencilElement {
    }
    var HTMLOrchestraButtonElement: {
        prototype: HTMLOrchestraButtonElement;
        new (): HTMLOrchestraButtonElement;
    };
    interface HTMLOrchestraIconElement extends Components.OrchestraIcon, HTMLStencilElement {
    }
    var HTMLOrchestraIconElement: {
        prototype: HTMLOrchestraIconElement;
        new (): HTMLOrchestraIconElement;
    };
    interface HTMLElementTagNameMap {
        "orchestra-button": HTMLOrchestraButtonElement;
        "orchestra-icon": HTMLOrchestraIconElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface OrchestraButton {
        /**
          * A boolean indicating the disable state of the button. The `aria-disabled` attribute relies on this property.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * It allows to render the chosen icon.  The icon render only if `iconName` and `iconPosition` are defined.
          * @default 'none'
         */
        "icon"?: 'only' | 'start' | 'end' | 'none';
        /**
          * Accept all icon names from
          * @pollux-docaposte /icon-library. By using the core-button component you don't have to install it as dependency.  The icon render only if `iconName` and `iconPosition` are defined.
          * @default undefined
         */
        "iconName"?: string;
        /**
          * The name of the element, used when submitting an HTML form.
         */
        "name"?: string;
        /**
          * A string indicating the size variation of the button.
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * This is the text which appear inside the button. It is required.
         */
        "text": string;
        /**
          * A string indicating the behavior of the button. It relies on `HTMLButtonElement['type']`
          * @default 'button'
         */
        "type"?: HTMLButtonElement['type'];
        /**
          * A string indicating the design variation of the button based on the level of importance.
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'tertiary';
    }
    interface OrchestraIcon {
        /**
          * Taking the currentcolor (inherited color of the font) by default, except if specified.
          * @default 'currentcolor'
         */
        "fill"?: string | 'currentcolor';
        /**
          * The name of the icon library to use. Defaults to 'core'.
          * @default 'core'
         */
        "library"?: string;
        /**
          * The name of the icon to display. Resolves using registered icon libraries.
         */
        "name": string;
        /**
          * Taking the size of the parent element by default, except if specified.
          * @default '100%'
         */
        "size"?: string | '100%';
    }

    interface OrchestraButtonAttributes {
        "text": string;
        "type": HTMLButtonElement['type'];
        "variant": 'primary' | 'secondary' | 'tertiary';
        "disabled": boolean;
        "size": 'small' | 'medium' | 'large';
        "icon": 'only' | 'start' | 'end' | 'none';
        "iconName": string;
    }
    interface OrchestraIconAttributes {
        "name": string;
        "library": string;
        "fill": string | 'currentcolor';
        "size": string | '100%';
    }

    interface IntrinsicElements {
        "orchestra-button": Omit<OrchestraButton, keyof OrchestraButtonAttributes> & { [K in keyof OrchestraButton & keyof OrchestraButtonAttributes]?: OrchestraButton[K] } & { [K in keyof OrchestraButton & keyof OrchestraButtonAttributes as `attr:${K}`]?: OrchestraButtonAttributes[K] } & { [K in keyof OrchestraButton & keyof OrchestraButtonAttributes as `prop:${K}`]?: OrchestraButton[K] } & OneOf<"text", OrchestraButton["text"], OrchestraButtonAttributes["text"]>;
        "orchestra-icon": Omit<OrchestraIcon, keyof OrchestraIconAttributes> & { [K in keyof OrchestraIcon & keyof OrchestraIconAttributes]?: OrchestraIcon[K] } & { [K in keyof OrchestraIcon & keyof OrchestraIconAttributes as `attr:${K}`]?: OrchestraIconAttributes[K] } & { [K in keyof OrchestraIcon & keyof OrchestraIconAttributes as `prop:${K}`]?: OrchestraIcon[K] } & OneOf<"name", OrchestraIcon["name"], OrchestraIconAttributes["name"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "orchestra-button": LocalJSX.IntrinsicElements["orchestra-button"] & JSXBase.HTMLAttributes<HTMLOrchestraButtonElement>;
            "orchestra-icon": LocalJSX.IntrinsicElements["orchestra-icon"] & JSXBase.HTMLAttributes<HTMLOrchestraIconElement>;
        }
    }
}
